// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArQ2_7idXnWcgvIH5I1x-LrTI2Psb-w3k',
    appId: '1:396648427779:ios:e20f355e090717d194f936',
    messagingSenderId: '396648427779',
    projectId: 'app-proyectos-firebase',
    storageBucket: 'app-proyectos-firebase.firebasestorage.app',
    iosBundleId: 'com.example.appProyectosFirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfGPYg_Lw_7IzPn7blG3Abm2OsZP121Yk',
    appId: '1:396648427779:web:7729fe580db8476794f936',
    messagingSenderId: '396648427779',
    projectId: 'app-proyectos-firebase',
    authDomain: 'app-proyectos-firebase.firebaseapp.com',
    storageBucket: 'app-proyectos-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArQ2_7idXnWcgvIH5I1x-LrTI2Psb-w3k',
    appId: '1:396648427779:ios:e20f355e090717d194f936',
    messagingSenderId: '396648427779',
    projectId: 'app-proyectos-firebase',
    storageBucket: 'app-proyectos-firebase.firebasestorage.app',
    iosBundleId: 'com.example.appProyectosFirebase',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClomOurXiHwgUGy7cdNS1Xa-UvWdMVlXc',
    appId: '1:396648427779:android:15b3c79d43719cc794f936',
    messagingSenderId: '396648427779',
    projectId: 'app-proyectos-firebase',
    storageBucket: 'app-proyectos-firebase.firebasestorage.app',
  );

}